export const PROBLEM_SERVICE_BASE_URL = import.meta.env.VITE_PROBLEM_SERVICE_URL;
export const SOCKET_SERVICE_BASE_URL = import.meta.env.VITE_SOCKET_SERVICE_URL;
export const EVALUATOR_SERVICE_BASE_URL = import.meta.env.VITE_EVALUATOR_SERVICE_URL;
export const SUBMISSION_SERVICE_BASE_URL = import.meta.env.VITE_SUBMISSION_SERVICE_URL;
